version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - "8001:8001"
    environment:
      - DB_URI=mongodb://user-db:27017/user-service
    depends_on:
      - user-db
    networks:
      - backend

  post-service:
    build: ./post-service
    ports:
      - "8002:8002"
    environment:
      - DB_URI=mongodb://post-db:27017/post-service
    depends_on:
      - post-db
    networks:
      - backend

  notification-service:
    build: ./notification-service
    ports:
      - "8003:8003"
    environment:
      - DB_URI=mongodb://notif-db:27017/notification-service
    depends_on:
      - notif-db
    networks:
      - backend

  # Separate MongoDB containers for each service
  user-db:
    image: mongo:latest
    container_name: user-db
    ports:
      - "27017:27017"
    volumes:
      - user-data:/data/db
    networks:
      - backend

  post-db:
    image: mongo:latest
    container_name: post-db
    ports:
      - "27018:27017"
    volumes:
      - post-data:/data/db
    networks:
      - backend

  notif-db:
    image: mongo:latest
    container_name: notif-db
    ports:
      - "27019:27017"
    volumes:
      - notif-data:/data/db
    networks:
      - backend

  gateway:
    build:
      context: ./gateway
    container_name: gateway
    ports:
      - "80:80"
    depends_on:
      - user-service
      - post-service
      - notification-service
    networks:
      - backend

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio-data:/data
    networks:
      - backend

volumes:
  user-data:
  post-data:
  notif-data:
  minio-data:

networks:
  backend:
    driver: bridge
